name: sync-main-to-dev

# author: @ralfhandl

#
# This workflow creates PRs to update the dev branch with the latest changes from main
#

# run this on push to main
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Generate access token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.OAI_SPEC_PUBLISHER_APPID }}
          private-key: ${{ secrets.OAI_SPEC_PUBLISHER_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Create pull request
        id: pull_request
        shell: bash
        run: |
          git config user.name ${GITHUB_ACTOR}
          git config user.email "a@b.c"
          SYNC="$BASE-sync-with-$HEAD"

          git fetch origin -v
          git checkout -b $SYNC origin/$SYNC || git checkout -b $SYNC origin/$BASE

          git merge origin/$HEAD -m "Merge $HEAD into $SYNC" --allow-unrelated-histories
          git checkout origin/dev src/*
          git checkout origin/dev tests/*
          git commit -m "Restored src/* and tests/*"
          git push -u origin $SYNC

          EXISTS=$(gh pr list --base $BASE --head $SYNC \
            --json number --jq '.[] | .number')
          if [ ! -z "$EXISTS" ]; then
            echo "PR #$EXISTS already wants to merge $SYNC into $BASE"
            exit 0
          fi

          gh pr create --base $BASE --head $SYNC \
            --label "Housekeeping" \
            --title "$BASE: sync with $HEAD" \
            --body "Merge relevant changes from \`$HEAD\` into \`$BASE\`."
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          HEAD: main
          BASE: dev
